### ISSUE TITLE
Problems with constrained Layout

### ISSUE THREAD

**Issue by znstrider** [znstrider/highlight_text#2]
```
import matplotlib.pyplot as plt
from highlight_text import *

fig, ax = plt.subplots(figsize=(4,4), constrained_layout=True)

text = ax_text(x=0., y=0.5, s='\nThis is an example\nshort <string>\nthat <messes up> somehow',
      ha='left', va='bottom', fontsize=32)

fig.set_facecolor('SkyBlue')
```

This for some reason doesn't show properly with constrained_layout=True.

**Comment by petermckeeverPerform** [comment]
This is an issue with font size. it looks like constrained layout will not push the figure to accomodate text that would overflow the boundaries of fig, so shifts text back. Possibly worth either noting that in docstring or considering alternative methods, but as pointed out by @znstrider, any resizing needs to be done **before** the text is drawn. 

A solution here could be to create (modify existing method in mpl) a function to redraw the plot and text after resizing?

**Comment by jklymak** [comment]
I don't know what this code particularly does, but if you want to take a text artist, or any other artist, out of the layout management, you can do `artist.set_in_layout(False)`.

**Comment by znstrider** [comment]
An easy fix seems to be to use fig_text in this case. This seems to work properly.

From the constrained_layout doc:
"An artist using axes coordinates that extend beyond the axes boundary will result in unusual layouts when added to an axes. This can be avoided by adding the artist directly to the Figure using add_artist(). See ConnectionPatch for an example."

Thanks for that suggestion @jklymak.
Setting text.set_in_layout(False) on all subtexts prevents the constrained layout from adjusting the figure size. If the text is too big, this will make it go beyond the figure.
This might be a good solution, but it will have to be tested to see if there are any downsides to this.

Btw, on a high level, the function
1) splits up text into rows
2) splits rows up by subtext delimiters
3) plots them seperately with individual colors (soon also bboxes, path effects)
4) aligns the positions of each subtext based on window_extent transformed into data coordinates

**Comment by jklymak** [comment]
Constrained layout doesn't adjust figure size.  It adjusts axes sizes if they are in a gridspec. 

Regardless the suggestion was simply to manually take any offending text out of the layout after they are made, not necessarily all of them, just like for any artist that overspills the bounds of the axes that you don't want to affect the layout.

**Comment by znstrider** [comment]
So usually the layout (ie. axes size) is adjusted when something overspills, and set_in_layout(False) prevents that for the artist this is called on, is that right?

Is there any downside to doing it for all texts, besides them then possibly overspilling the axes bounds?

**Comment by jklymak** [comment]
constrained layout makes room between axes for any decorations on the axes (tick labels, xlabels, etc).  If a text box over-spills an axes, constrained layout will shrink all the axes to make room for it.  

If you think all your texts are just going to be used for annotations, and its OK for the annotations to overspill their axes and cover up other axes, then it should be fine to take them out of the layout.  Note the user can still put them back in the layout if you give them the handle to the text object.
