### ISSUE TITLE
Can't import HighlightText

### ISSUE THREAD

**Issue by JackyKch** [znstrider/highlight_text#4]
Hi, while trying to import the library, I came across an error. 
I was running the following command in a notebook

``` python
from highlight_text import HighlightText
```
which returned me this : 

```
cannot import name 'HighlightText' from 'highlight_text'
```

I tried reinstalling the library using the following :
``` 
pip install highlight-text
```
But in the end, it didn't work out. I couldn't find any solution to this problem. (I'm using Python 3.9.0)

Apologies in advance if I'm missing something!

**Comment by JackyKch** [comment]
Hi, sorry again !

After uninstalling the package using 

``` 
py -m pip uninstall highlight_text
```

And then reinstalling it with pip, everything seems to work fine now.

Thanks again !

**Comment by znstrider** [comment]
Glad you got it to work!
